.circleci/config.yml
- Creates Docker Image
- Docker Image gets pushed to Docker Hub
- Tagged Image gets pulled from Docker Hub onto Digital Ocean
#19 
- With `steps` heading added `setup_remote_docker` so that the image can be saved
- Change the path where the cache is saved to $HOME directory
- Added steps to build, save, and run Docker Image
- Added step to deploy Docker Image to Docker Hub using Docker Hub account info saved in environment variables
=> Part 1: CircleCI builds Docker image and pushes to Docker Hub

.circleci/config.yml
- Docker image was not caching correctly on .circleci, this change should decrease build times.
- Edit .circleci file
=> Fix image caching

README.md
- Add the circleci badge
- Add the staging url
#47
=> Add CircleCI badge and staging url

.circleci/config.yml
- Tests are now only run on PRs and docker images aren't built
- Docker image is built once commit is merged into master or staging-* branches
#45
=> Make docker image only build on master and staging

Gemfile, Gemfile.lock, app/assets/javascripts/dashboard.coffee, app/assets/stylesheets/dashboard.scss, app/controllers/dashboard_controller.rb, app/helpers/dashboard_helper.rb, app/models/user.rb, app/views/dashboard/show.html.erb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20180927215719_devise_create_users.rb, db/schema.rb, spec/controllers/dashboard_controller_spec.rb, spec/helpers/dashboard_helper_spec.rb, spec/models/user_spec.rb, yarn.lock
- Added login authentication
- Added signup page
- Added "forgot password" page
- Added Dashboard view
#34 
#35 
- Added devise gem
- Migrated database
- Generated devise user
- Generated devise views
- Configured routes when the user is authenticated they view Dashboard when they are not they view sign up
- Generated dashboard controller and view
=> Setup devise

config/routes.rb
-fixed redirect within routes.db
-there was a redirect issue so it was fixed by moving the "devise_for: users" to its proper spot
=> Fix redirect

README.md, docker-compose.yml, ops/dev/Dockerfile, script/start
- Adds local docker documentation to README.md
#15
=> Add local docker documentation

app/assets/stylesheets/homepage.scss, app/views/homepage/show.html.erb
Navigation Bar Dropdown Menus
https://github.com/ChapmanCPSC/SE-Society/issues/27
=> Issue 27: Nav Bar Creation

spec/factories/factories.rb, spec/features/user/register_spec.rb
- This tests the user registration
#71
- Registration should fail if the password is too short or if the passwords don't match
- Registration should succeed if passwords both match
=> Add user registration test

app/assets/stylesheets/homepage.scss, app/assets/stylesheets/nav_bar.scss, app/controllers/professional_development_controller.rb, app/controllers/standards_resources_controller.rb, app/views/homepage/show.html.erb, app/views/professional_development/books.html.erb, app/views/professional_development/exams.html.erb, app/views/professional_development/future.html.erb, app/views/standards_resources/conduct.html.erb, app/views/standards_resources/demographics.html.erb, app/views/standards_resources/podcasts.html.erb, app/views/standards_resources/scoring.html.erb, app/views/standards_resources/standards.html.erb, config/routes.rb
Clicking on the menus from the nav bar takes you to their own page with a consistent nav bar at the top
https://github.com/ChapmanCPSC/SE-Society/issues/27
https://github.com/ChapmanCPSC/SE-Society/issues/31
https://github.com/ChapmanCPSC/SE-Society/issues/30
Added a new controller for each menu item and new views for each submenu
=> Populate nav menus

Gemfile, Gemfile.lock, app/admin/dashboard.rb, app/admin/user.rb, app/models/ahoy/event.rb, app/models/ahoy/visit.rb, config/initializers/ahoy.rb, db/migrate/20181017212324_create_ahoy_visits_and_events.rb, db/schema.rb
- Admin can see number of users registered on `/admin`
- Admin can create new users with first name, last name, and username (blocked by #78)
- Admin can see number of website views on `/admin`
#37 
- Add ahoy_matey gem
- Add panels to activeadmin dashboard
=> Add statistics to admin dashboard

app/controllers/future_engineers_controller.rb, app/views/future_engineers/info.html.erb, app/views/future_engineers/life.html.erb, app/views/future_engineers/paths.html.erb, app/views/homepage/show.html.erb, app/views/professional_development/exams.html.erb, app/views/professional_development/future.html.erb, app/views/standards_resources/conduct.html.erb, app/views/standards_resources/demographics.html.erb, app/views/standards_resources/podcasts.html.erb, app/views/standards_resources/scoring.html.erb, app/views/standards_resources/standards.html.erb, config/routes.rb
Populated the Future Software Engineer Menu
https://github.com/ChapmanCPSC/SE-Society/issues/29
Added controller and views for the different submenus
=> Populating the Future Software Engineers Menu

.gitignore, db/migrate/20181018043959_add_user_details.rb, db/schema.rb, db/seeds.rb
- Add some seed data for UserDetails
https://github.com/ChapmanCPSC/SE-Society/issues/70
- Made a new migration
- Modified schema.rb and seeds.rb.
=> Add seed data

app/assets/stylesheets/homepage.scss, app/views/homepage/show.html.erb
CSS of homepage changed for better styling
https://github.com/ChapmanCPSC/SE-Society/issues/64
- CSS colors/fonts/backgrounds
=> Changed CSS Homepage

app/views/homepage/show.html.erb
Add LinkedIn embedded plugin
Added LinkedIn embedded plugin to homepage.
https://github.com/ChapmanCPSC/SE-Society/issues/33
- Added LinkedIn embedded plugin to homepage.
=> Add LinkedIn job feed to homepage

app/views/about/description.html.erb, app/views/about/goals.html.erb, app/views/about/membership.html.erb, app/views/dashboard/show.html.erb, app/views/future_engineers/info.html.erb, app/views/future_engineers/life.html.erb, app/views/future_engineers/paths.html.erb, app/views/homepage/show.html.erb, app/views/professional_development/books.html.erb, app/views/professional_development/exams.html.erb, app/views/professional_development/future.html.erb, app/views/standards_resources/conduct.html.erb, app/views/standards_resources/demographics.html.erb, app/views/standards_resources/podcasts.html.erb, app/views/standards_resources/scoring.html.erb, app/views/standards_resources/standards.html.erb
Users will be able to click on the title, "Society of Software Engineers" on any page of the website and be brought back to the home page.
#103 
Ex:
- Title pages is linked to the homepage
=> added clickable home logo button on all pages

app/assets/stylesheets/page.scss, app/views/future_engineers/info.html.erb, app/views/future_engineers/life.html.erb, app/views/future_engineers/paths.html.erb
Populating the Future Engineers submenus with their content
https://github.com/ChapmanCPSC/SE-Society/issues/99
=> Future engineers

app/views/professional_development/books.html.erb
Added content to the books tab
#100
Added html and css to the books tab
=> added books content

app/assets/stylesheets/homepage.scss, app/assets/stylesheets/page.scss, app/views/dashboard/show.html.erb, app/views/homepage/show.html.erb, app/views/professional_development/exams.html.erb, config/routes.rb
1 - Added content under Professional Development tab in the exams and certifications section
2 - Updated the homepage routing when users are signed in or not. 
#100 & #107 
Ex:
- Updated the exams.html file with the content I researched
- When a user first enters our website he/she is routed to the homepage.show.html file and also when he/she logs in or signs up they will be routed to the same file
=> Home page exams

app/views/future_engineers/info.html.erb, app/views/future_engineers/life.html.erb, app/views/future_engineers/paths.html.erb, app/views/professional_development/books.html.erb, app/views/professional_development/exams.html.erb, app/views/professional_development/future.html.erb, app/views/standards_resources/conduct.html.erb, app/views/standards_resources/demographics.html.erb, app/views/standards_resources/podcasts.html.erb
Added drop down menu names to the AboutSoSE tab
#100 
Ex:
- updated drop down menu names
=> updated dropdown menus on all tabs

app/views/professional_development/books.html.erb, app/views/professional_development/future.html.erb
Fixed styling errors under the professional development tab
#100 
Ex:
Made the information under the professional development tab look nice
=> updated css on content page
